language: ruby
# only run CI-builds on src branch
branches:
  only:
  - src
rvm:
- 2.2.7
# set execution permission on our build script
before_script:
 - chmod +x ./scripts/cibuild
# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./scripts/cibuild
exclude: [vendor]
sudo: false
