# Site
repository: Cheukting/Cheukting.github.io
# favicon: images/favicon.ico

# Personal info
name: Cheuk Ting Ho
title: Building the Open-source Community
email:
phone:
website:
description: >
  Cheuk constantly contributes to the open-source community by giving AI and deep learning workshops and organize sprints to encourage diversity contributions.
url: https://cheuk.dev
baseurl: ""
permalink: /:year/:month/:day/:title/

# Social links
twitter_username: cheukting_ho
github_username:  Cheukting
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: cheukting-ho
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
medium_username:
devto_username: cheukting_ho
twitch_username: cheukting_ho

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_1037.jpg
about_content: | # this will include new lines to allow paragraphs
    After spending 5 years researching theoretical physics at [Hong Kong University of Science and Technology](https://www.ust.hk/home), Cheuk has transferred her analytical and logical skills in natural science and built a career in data science. Cheuk has been a Data Scientist in one of the biggest worldwide wholesalers in the travel business;  an AWS partnered consultancy which delivers machine learning model; a startup aiming to revolutionise revenue management with data science and; a global bank using machine learning to investigating financial crime. Now Cheuk is working in a team of developers building a [revolutionary graph database](https://terminusdb.com/).

    Cheuk constantly contributes to the community by giving AI and deep learning workshops and [organize sprints](https://python-sprints.github.io/) for open source projects, at the same time contribute to open source projects including Pandas, Keras, Scikit-learn, Dateutil and maintaining her open-source library - [PicknMix](https://picknmix.readthedocs.io/en/latest/). Cheuk has also been a guest speaker at Universities and various conferences. Believing in gender equality, Cheuk is currently a co-organizer of [AI Club for Gender Minorities](https://www.meetup.com/ai-club/) to support Tech Diversity and Inclusion. On top of speaking at conferences, Cheuk has join the organizing team of EuroPython, IndieWebCamp and PyData London.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Talks #(Use this to override about experience section title)

# Education Section
education_title: Workshops #(Use this to override about education section title)

meetups_title: Meetups / Events

# More Section
more_title: Invite me to speak? #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I am happy to speak at conferences/ meetups / events, or facilitate the above workshops for the community. You can contact me via [Twitter](https://twitter.com/cheukting_ho) or [LinkedIn](https://www.linkedin.com/in/cheukting-ho).

# Footer
footer_show_references: true

# Author settings
author:
  - name: Cheuk Ting Ho
    bio: After having a career in data science, Cheuk now brings her knowledge in data and passion for the tech community into TerminusDB as the developer relations lead. Cheuk constantly contributes to the open-source community by giving AI and deep learning workshops and organize sprints to encourage diversity contributions.
    url: https://cheuk.dev

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 3
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

page_gen-dirs: true

page_gen:
  - data: 'videos'
    template: 'video'
    name: 'vid'
    dir: 'videos'
    paginate: 3
    paginate_template: 'videos-page'

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-paginate-v2
 - jekyll-sitemap
 - jekyll-linkpreview
# - data_page_generator

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "package.json",
  "gulpfile.js",
  "scripts/",
  ]
